Autor: **Gabriel Olmos Leiva**

## **Tabla de contenido**

1. PyTorch.

## **1. PyTorch**

### **1.1 Instalar PyTorch**

Para instalar PyTorch es necesario tener una GPU, luego debes derigirte a la [documentación oficial](https://pytorch.org) y seleccionar el sistema operativo que tienes, si utilizas conda o pip, etc. En mi caso, seleccioné lo que se muestra en la imagen abajo.

**Nota**: PyTorch también se puede programar en C++ utilizando el módulo llamado Torchlib.

![Instalación PyTorch](../../assets/torch_1.png)

Verificamos que no tenemos torch

In [1]:
!pip show torch

Instalamos torch utilizando el comando que nos entregó la página de pytorch. Nota, agregué ! y elminé el 3 de pip.

In [2]:
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124

Looking in indexes: https://download.pytorch.org/whl/cu124
     ---------------------------------------- 0.0/6.2 MB ? eta -:--:--
     ---------------------- ----------------- 3.4/6.2 MB 18.4 MB/s eta 0:00:01
     ---------------------------------------- 6.2/6.2 MB 20.0 MB/s eta 0:00:00
  Using cached https://download.pytorch.org/whl/mpmath-1.3.0-py3-none-any.whl (536 kB)
  Using cached https://download.pytorch.org/whl/MarkupSafe-2.1.5-cp310-cp310-win_amd64.whl (17 kB)
   ---------------------------------------- 0.0/2.5 GB ? eta -:--:--
   ---------------------------------------- 0.0/2.5 GB 29.7 MB/s eta 0:01:26
   ---------------------------------------- 0.0/2.5 GB 34.9 MB/s eta 0:01:13
   ---------------------------------------- 0.0/2.5 GB 37.3 MB/s eta 0:01:08
    --------------------------------------- 0.0/2.5 GB 41.0 MB/s eta 0:01:01
    --------------------------------------- 0.0/2.5 GB 41.0 MB/s eta 0:01:01
    --------------------------------------- 0.1/2.5 GB 39.9 MB/s eta 0:0

In [1]:
!pip show torch

Name: torch
Version: 2.7.1+cu118
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3-Clause
Location: C:\Users\gol_m\anaconda3\envs\eie_iag\Lib\site-packages
Requires: filelock, fsspec, jinja2, networkx, setuptools, sympy, typing-extensions
Required-by: torchaudio, torchvision


#### **1.1.1 Importar torch**

In [2]:
import torch

#### **1.1.2 Verificar que estamos utilizando la GPU**

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [7]:
torch.__version__

'2.6.0+cu124'

In [8]:
!nvidia-smi

Sun Feb 16 20:30:34 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 561.09                 Driver Version: 561.09         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1050      WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   49C    P8             N/A /   30W |       0MiB /   4096MiB |      1%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### **1.2 Introducción a Tensores**

Cuando trabajamos con el framework PyTorch, utilizamos **tensores**. El tensor hace referencia a un escalar, vector, matriz, etc, dependiendo de su dimensión. Por otro lado, cuando estamos programando es importante aprender los **atributos** más relevantes de los tensores, como:

1. ``tensor.ndim``
2. ``tensor.dtype``
3. ``tensor.shape``
4. ``tensor.device``

Por último, aprender algunos métodos:

1. ``tensor.size()``
2. ``tensor.item()``


#### **1.2.1 Escalares (Tensores 0D)**

In [4]:
escalar = torch.tensor(7)

In [ ]:
# Muestra el tensor

In [6]:
# Podemos mostrar la dimensión del tensor
# escalar.ndim

In [6]:
# Podemos ver el tamaño del tensor
# escalar.size()

In [7]:
# Podemos mostrar el tipo de dato del tensor
# escalar.dtype

In [8]:
# Podemos ver la forma del tensor o la cantidad de elementos
# escalar.shape

In [ ]:
# Podemos convertirlo a un entero de python
escalar.item()

#### **1.2.2 Vectores (Tensores 1D)**

In [9]:
vector = [7, 5, 3, 1]

tensor = torch.tensor(vector)

In [11]:
# tensor

In [ ]:
# Muestra el tensor

In [12]:
# Muestra la dimensión del tensor
# tensor.ndim

In [13]:
# Muestra el tamaño del tensor
# tensor.size()

In [14]:
# Muestra  el tipo de dato del tensor
# tensor.dtype

In [15]:
# Muestra la forma del tensor o la cantidad de elementos
# tensor.shape

#### **1.2.3 Matriz (Tensores 2D)**

In [38]:
m = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

matrix = torch.tensor(m)

In [ ]:
# Muestra el tensor, su tamaño, su dimensión, su tipo de dato, su forma.

#### **1.2.4 Tensores 3D**

In [31]:
v = [[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]]

tensor = torch.tensor(v)

In [16]:
# tensor

In [17]:
# tensor.shape

In [ ]:
v2 = [[
    [1,2,3],
    [4,5,6],
    [7,8,9]],
[
    [6,5,3],
    [6,5,6],
    [6,8,9]]
]

tensor = torch.tensor(v2)

In [18]:
# tensor.shape

In [19]:
# tensor.ndim

Podemos ver esto como una secuencia de matrices.

#### **1.2.5 Tensores 4D**

Un ejemplo de tensores en 3D puede ser una secuencia de imágenes (matrices) a color.

In [41]:
v = [[[
    [1,2,3],
    [4,5,6],
    [7,8,9]],
[
    [6,5,3],
    [6,5,6],
    [6,8,9]]
]]

tensor = torch.tensor(v)

In [20]:
# tensor.ndim

In [21]:
# tensor.shape

![imagen](../../assets/color_image_representation.png)

#### **1.2.6 Tensores Aleatorios (Random Tensor)**

In [18]:
random_tensor_1d = torch.rand(6) # Recuerda que los argumentos representan la fila
# random_tensor_1d

In [20]:
random_tensor_2d = torch.rand(3,4) # Recuerda que los argumentos representan la fila y columna del tensor
# random_tensor_2d

In [22]:
# Ahora crearé un tensor 3D, es decir una secuencia de 3 matrices 
random_tensor_3d = torch.rand(3,4,4) 
# random_tensor_3d

In [23]:
# Ahora crearé un tensor 3D, es decir una secuencia de 3 matrices 
random_tensor_4d = torch.rand(3,4,4,3) 
# random_tensor_4d

In [22]:
# random_tensor_4d.shape

##### **Tensores deterministas**

Podemos replicar los valores obtenidos de un tensor aleatorio

In [31]:
random_tensor_1d = torch.rand(6) # Recuerda que los argumentos representan la fila
random_tensor_1d

tensor([0.3581, 0.5651, 0.3963, 0.1969, 0.3205, 0.8569])

In [34]:
torch.manual_seed(5)

random_tensor_1d = torch.rand(6) # Recuerda que los argumentos representan la fila
random_tensor_1d

tensor([0.8303, 0.1261, 0.9075, 0.8199, 0.9201, 0.1166])

In [50]:
torch.manual_seed(5)
random_tensor_1d = torch.rand(8) # Recuerda que los argumentos representan la fila
random_tensor_1d

tensor([0.8303, 0.1261, 0.9075, 0.8199, 0.9201, 0.1166, 0.1644, 0.7379])

#### **1.2.7 Zeros & Ones**

In [47]:
unos_1d = torch.ones(5)
unos_2d = torch.ones(5, 5)

In [50]:
# Muestra los tensores

In [51]:
zeros_1d = torch.zeros(5)
zeros_2d = torch.zeros(3,3)

In [54]:
# Muestra los tensores

#### **1.2.8 Rango de tensores**

##### **linspace()**

| [Ver documentación](https://pytorch.org/docs/stable/generated/torch.linspace.html#torch-linspace) |

In [66]:
range = torch.linspace(0,10,10)

In [ ]:
# Muestra el tensor generado

##### **arange()**

| [Ver documentación](https://pytorch.org/docs/stable/generated/torch.arange.html) |

In [55]:
range = torch.arange(0,10,1)

In [ ]:
# Muestra el tensor generado

#### **1.2.9 Tensors-like**

In [71]:
tensor = torch.arange(0,10,1, dtype=torch.uint8)

In [23]:
# tensor.dtype

In [75]:
test_tensor = torch.arange(0,10,1)

In [24]:
# test_tensor.dtype

In [25]:
ones_tensor = torch.ones_like(tensor)
# ones_tensor

In [ ]:
test_ones_tensor = torch.ones_like(test_tensor)
# test_ones_tensor

#### **1.3.1 Tipo de datos en los tensores (Tensors-dtype)**

Existen distintos tipos de datos, se puede revisar la [documentación](https://pytorch.org/docs/stable/tensors.html) para obtener más información.

In [80]:
float_32_tensor = torch.tensor([5, 4, 3], dtype=torch.float32)

In [ ]:
# Visualizar el tensor y mostrar su tipo de dato

In [83]:
float_16_tensor = torch.tensor([5, 4, 3], dtype=torch.float16)

In [ ]:
# Visualizar el tensor y mostrar su tipo de dato

In [85]:
bifloat16_tensor = torch.tensor([5, 4, 3], dtype=torch.bfloat16)

In [ ]:
# Visualizar el tensor y mostrar su tipo de dato

In [87]:
int8_tensor = torch.tensor([5, 4, 3], dtype=torch.int8)

In [ ]:
# Visualizar el tensor y mostrar su tipo de dato

#### **1.3.2 Información de los tensores**

In [ ]:
some_tensor = torch.rand(3, 4)

print(some_tensor)
print(f"Shape del tensor: {some_tensor.shape}")
print(f"Datatype del tensor: {some_tensor.dtype}")
print(f"Device del tensor: {some_tensor.device}") # will default to CPU

In [ ]:
device

In [ ]:
some_tensor_gpu = torch.rand(3, 4, device=device)

print(some_tensor)
print(f"Shape del tensor: {some_tensor_gpu.shape}")
print(f"Datatype del tensor: {some_tensor_gpu.dtype}")
print(f"Device del tensor: {some_tensor_gpu.device}") # will default to CPU

### **1.3 Operando con los Tensores**

#### **1.3.1 Operaciones básicas**

Las operaciones suma, resta, multiplicación se hacen elemento a elementos.

In [3]:
tensor = torch.tensor([1, 2, 3])

In [4]:
suma = tensor + 10
resta = tensor - 1
mul = tensor * 2

In [ ]:
# Muestra el resultado

In [98]:
suma = tensor.add(10)
resta = tensor.sub(1)
mult = tensor.multiply(2)

In [ ]:
# Muestra el resultado

#### **1.3.2 Multiplicación Matricial**

Para empezar debemos recordar la multiplicación matricial.

Dadas dos matrices $A$ y $B$, su producto $ C = A \times B $ es posible si el número de columnas de $ A $ es igual al número de filas de $ B $.  

Si $ A $ es de dimensión $ m \times n $ y $ B $ es de dimensión $ n \times p $, entonces $ C $ tendrá dimensión $ m \times p $.  

Cada elemento $ C_{ij} $ de la matriz resultante se obtiene como la suma del producto de los elementos de la fila $ i $ de $ A $ por los elementos de la columna $ j $ de $ B $:

$$
C_{ij} = \sum_{k=1}^{n} A_{ik} B_{kj}
$$

Ejemplo:  

$$
A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}, \quad
B = \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix}
$$

Multiplicamos filas por columnas:

$$
C = \begin{bmatrix} (1\times5 + 2\times7) & (1\times6 + 2\times8) \\ (3\times5 + 4\times7) & (3\times6 + 4\times8) \end{bmatrix}
$$

$$
C = \begin{bmatrix} 19 & 22 \\ 43 & 50 \end{bmatrix}
$$

In [35]:
a = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

b = [
    [1, 2],
    [3, 4],
    [5, 6]
]

matrix_a = torch.tensor(a)
matrix_b = torch.tensor(b)

c = matrix_a @ matrix_b

Esta operación matricial se está realizando en la CPU.

In [36]:
# c.device

In [ ]:
matrix_a.shape

In [ ]:
matrix_b.shape

In [ ]:
# Muestra el resultado

Verifiquemos la forma de cada matriz y el resultado.

In [ ]:
print("Forma de a:", matrix_a.shape)
print("Forma de b:", matrix_b.shape)
print("Forma de c:", c.shape)

In [12]:
mul_1 = torch.matmul(matrix_a, matrix_b)

In [ ]:
mul_1

#### **1.3.3 Producto Punto**

In [39]:
tensor_1 = torch.tensor([1, 2, 3])
tensor_2 = torch.tensor([3, 3, 3])

In [40]:
dot_product_1 = tensor_1 @ tensor_2 
dot_product_2 = torch.dot(tensor_1, tensor_2)
dot_product_3 = torch.matmul(tensor_1, tensor_2)

In [ ]:
# Muestra el resultado

#### **1.3.4 Transpuesta**

In [ ]:
tensor_1 = torch.tensor([[1, 2, 3]])
tensor_1

In [ ]:
# Transpuesta utilizando el método 1
transpuesta_m1 = tensor_1.T
transpuesta_m1

In [ ]:
# Transpuesta utilizando el método 2
transpuesta_m2 = torch.transpose(tensor_1, 1, 0)
transpuesta_m2

In [ ]:
tensor_2 = torch.tensor([[1, 2, 3], [5, 5, 5]])
tensor_2

In [ ]:
tran_1 = torch.transpose(tensor_2, 0, 1)
tran_1

In [ ]:
tran_2 = tensor_2.T
tran_2

#### **1.3.5 Red Neuronal**

En PyTorch vienen implementada las redes neuronales artificiales. Para llamarlas debemos utilizar el módulo nn.

In [6]:
import torch.nn as nn

In [10]:
capa = nn.Linear(3, 6)  # 3 entradas → 6 salidas
# capa

In [ ]:
x = torch.tensor([1.0, 2.0, 3.0])
salida = capa(x)

print(salida)

Veamos otro ejemplo con otra red neuronal

In [ ]:
lstm = nn.LSTM(input_size=3, hidden_size=5, batch_first=True)

# (batch, secuencia, características)
x = torch.randn(1, 4, 3)

salida, (h_n, c_n) = lstm(x)

print(salida.shape)  # (1, 4, 5)

In [ ]:
conv = nn.Conv2d(in_channels=1, out_channels=3, kernel_size=3)

# (batch, canales, alto, ancho)
x = torch.randn(1, 1, 5, 5)

salida = conv(x)

print(salida.shape)

#### **1.3.6 min, max, mean, sum**

In [55]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Obtener el mínimo del tensor
x.min()

In [ ]:
# Obtener el máximo del tensor
x.max()

In [ ]:
# Obtener la media del tensor
x.mean()

In [ ]:
# Obtener la media del tensor
x.type(torch.float32).mean()

In [ ]:
# Obtener la suma
x.sum()

In [ ]:
# Obtener la suma
sum(x)

#### **1.3.7 Positional min/max (Obtener índice del tensor)**

In [62]:
x = torch.arange(10, 110, 10)
x

tensor([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
print(f"Tensor: {x}")
print(f"Índice del valor máximo del tensor: {x.argmax()}")
print(f"Índice del valor mínimo del tensor: {x.argmin()}")

#### **1.3.8 Cambiar el tipo de dato**

In [ ]:
tensor = torch.arange(10., 100., 10.)
tensor.dtype

In [ ]:
f16 = tensor.type(torch.float16)
f16.dtype

In [ ]:
tensor_2 = torch.tensor([1, 255, 256, 257])
tensor_2.dtype

In [71]:
tensor_u8 = tensor_2.type(torch.uint8)

### **1.4 Operaciones Avanzadas**

#### **1.4.1 Reshape**

Es común tener que cambiar la forma de los tensores, dado que se espera de cierta forma un tensor y se debe convertir a otra dimensión.

El método `reshape()` cambia la forma (dimensiones) de un tensor sin cambiar sus datos. Si los nuevos tamaños no son compatibles con el número de elementos en el tensor original, lanzará un error. A diferencia de view(), reshape() puede realizar copias de los datos si es necesario.

In [2]:
x = torch.linspace(1, 10, 10) # Creamos un tensor que contenga 10 elementos
x

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [7]:
x.shape

torch.Size([10])

In [19]:
matrix = [list(range(1,10))]
matrix
z = torch.tensor(matrix, dtype=torch.float32)
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [20]:
z.dtype

torch.float32

Podemos apreciar `x` es un tensor 1D y  `z` es un tensor 2D. Podemos verificar lo siguiente:

* x tiene la forma (10, )
* z tiene la forma (1, 9). 

Si hago una multiplicación matricial, ¿Qué ocurre?.

In [9]:
# Intentaremos hacer la multiplicación matricial con matmul
mm = torch.matmul(x, z)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x10 and 1x9)

In [10]:
# Intentaremos hacer la multiplicación matricial con mm
mm = torch.mm(x, z)

RuntimeError: self must be a matrix

El problema es la forma de estos tensores, para solucionar este problema debemos hacer un `reshape`.

* x tiene la forma (10,) y lo convertiremos a la forma (10,1), visto de otro modo, convertiremos un vector de diez elementos a una matriz con diez filas y una columna.

In [11]:
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [12]:
reshape_x = x.reshape(10, 1)
reshape_x

tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])

In [13]:
# verifica la forma
reshape_x.shape

torch.Size([10, 1])

In [21]:
reshape_x.dtype

torch.float32

In [22]:
z.dtype

torch.float32

In [23]:
# Ahora multipliquemos
mm = torch.matmul(reshape_x, z)
mm

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
        [ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.],
        [ 4.,  8., 12., 16., 20., 24., 28., 32., 36.],
        [ 5., 10., 15., 20., 25., 30., 35., 40., 45.],
        [ 6., 12., 18., 24., 30., 36., 42., 48., 54.],
        [ 7., 14., 21., 28., 35., 42., 49., 56., 63.],
        [ 8., 16., 24., 32., 40., 48., 56., 64., 72.],
        [ 9., 18., 27., 36., 45., 54., 63., 72., 81.],
        [10., 20., 30., 40., 50., 60., 70., 80., 90.]])

Como puedes apreciar, nos entregó un error que nos indica que no podemos realizar la multiplicación dado a que tienen distinto tipo de datos.

In [ ]:
# verifica el tipo de dato

In [21]:
# reshape_x.dtype

In [23]:
# z.dtype

Vamos a convertir `z` a un float32 y debemos ahora obtener una matriz 10x9, es decir, 90 elementos.

In [ ]:
mm = torch.mm(reshape_x, z.type(torch.float32))
mm

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
        [ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.],
        [ 4.,  8., 12., 16., 20., 24., 28., 32., 36.],
        [ 5., 10., 15., 20., 25., 30., 35., 40., 45.],
        [ 6., 12., 18., 24., 30., 36., 42., 48., 54.],
        [ 7., 14., 21., 28., 35., 42., 49., 56., 63.],
        [ 8., 16., 24., 32., 40., 48., 56., 64., 72.],
        [ 9., 18., 27., 36., 45., 54., 63., 72., 81.],
        [10., 20., 30., 40., 50., 60., 70., 80., 90.]])

In [106]:
mm.numel()

90

#### **1.4.2 Stack**

El método ``stack()`` apila (concatena) una secuencia de tensores a lo largo de una nueva dimensión. Todos los tensores deben tener las mismas dimensiones, excepto en la dimensión en la que se realiza la concatenación.

In [46]:
torch.manual_seed(5)

random_tensor = torch.rand(size=(1,3), dtype=torch.bfloat16)
random_tensor

tensor([[0.3867, 0.8047, 0.9336]], dtype=torch.bfloat16)

In [47]:
random_tensor.ndim

2

Ahora vamos a concatenar el tensor aleatorio de 2x3 hacia abajo, utilizando dim=0. Esto nos creará 3 muestras o ejemplos del mismo tensor, obteniendo la forma (3, 1, 3)

In [48]:
x_stacked = torch.stack([random_tensor, random_tensor, random_tensor], dim=0)
x_stacked

tensor([[[0.3867, 0.8047, 0.9336]],

        [[0.3867, 0.8047, 0.9336]],

        [[0.3867, 0.8047, 0.9336]]], dtype=torch.bfloat16)

In [26]:
# Muestra el resultado
x_stacked

tensor([[[0.8555, 0.8164, 0.2500]],

        [[0.8555, 0.8164, 0.2500]],

        [[0.8555, 0.8164, 0.2500]]], dtype=torch.bfloat16)

In [33]:
x_stacked.shape

torch.Size([3, 1, 3])

Ahora vamos a concatenar el tensor aleatorio de 2x3 en una misma matriz, utilizando dim=1. Esto nos dará como resultado una forma de (1, 3, 3)

In [ ]:
y_stacked = torch.stack([random_tensor, random_tensor, random_tensor], dim=1)
y_stacked

tensor([[[0.3867, 0.3867, 0.3867],
         [0.8047, 0.8047, 0.8047],
         [0.9336, 0.9336, 0.9336]]], dtype=torch.bfloat16)

In [42]:
y_stacked.shape

torch.Size([1, 3, 3])

In [43]:
# Muestra el resultado
y_stacked

tensor([[[0.8555, 0.8555, 0.8555],
         [0.8164, 0.8164, 0.8164],
         [0.2500, 0.2500, 0.2500]]], dtype=torch.bfloat16)

#### **1.4.3 Squeeze**

Elimina las dimensiones de tamaño 1 de un tensor. Por ejemplo, si tienes un tensor de forma ``(1, 3, 1, 5)``, usar ``squeeze()`` eliminará las dimensiones que tienen un tamaño de 1, quedando un tensor de forma ``(3, 5)``.

In [51]:
torch.manual_seed(5)

random_tensor = torch.rand(size=(1,3), dtype=torch.bfloat16)

print("Vemos la dimensión del tensor:", random_tensor.ndim)
print("Vemos la forma del tensor:", random_tensor.shape)

Vemos la dimensión del tensor: 2
Vemos la forma del tensor: torch.Size([1, 3])


In [53]:
random_tensor

tensor([[0.3867, 0.8047, 0.9336]], dtype=torch.bfloat16)

In [52]:
y_stacked = torch.stack([random_tensor, random_tensor, random_tensor], dim=1)

print("Vemos la dimensión del tensor:", y_stacked.ndim)
print("Vemos la forma del tensor:", y_stacked.shape)

Vemos la dimensión del tensor: 3
Vemos la forma del tensor: torch.Size([1, 3, 3])


In [57]:
y_stacked

tensor([[[0.3867, 0.8047, 0.9336],
         [0.3867, 0.8047, 0.9336],
         [0.3867, 0.8047, 0.9336]]], dtype=torch.bfloat16)

In [58]:
y_stacked.ndim

3

Podemos apreciar que se agregó una dimensión extra, también conocida como la dimensión del batch. ¿Podemos eliminar esa dimensión?, la respuesta es sí, podemos eliminar la dimensión del batch.

In [55]:
y_stacked_squeeze = y_stacked.squeeze()

In [59]:
# Muestra cómo quedó el tensor y visualiza la forma
y_stacked_squeeze.ndim

2

Si podemos eliminar una dimensión, ¿Podemos volver agregar la dimensión?

In [60]:
y_stacked_unsqueeze = y_stacked_squeeze.unsqueeze(dim=0)

In [62]:
# Muestra el resultado y juega utilizando dim=1, dim=2
y_stacked_unsqueeze.ndim

3

#### **1.4.4 Permutar**

El método `permute()` reorganiza las dimensiones de un tensor. Este método permite cambiar el orden de las dimensiones del tensor, especificando una nueva secuencia de índices.

In [65]:
x_original = torch.rand(size=(224, 28, 28))

# Permutar nos permite mover los ejes
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Shape del tensor original: {x_original.shape}")
print(f"Shape del tensor permutado: {x_permuted.shape}")

Shape del tensor original: torch.Size([224, 28, 28])
Shape del tensor permutado: torch.Size([28, 224, 28])


#### **1.4.5 Unsqueeze**

Agrega una nueva dimensión de tamaño 1 en una posición específica del tensor. Esto es útil cuando necesitas expandir un tensor para que encaje en una operación que requiere una forma específica.

In [1]:
import torch

In [3]:
# creamos un tensor
x = torch.randn(3,5)

In [ ]:
# Verifique la forma

In [ ]:
x_unsqueezed = x.unsqueeze(0)  # Añade una nueva dimensión en el eje 0

In [ ]:
# Muestre la forma del nuevo tensor

#### **1.4.6 Concatenación**

Concatena una secuencia de tensores a lo largo de una dimensión especificada. Los tensores deben tener el mismo tamaño en todas las dimensiones excepto en la dimensión de concatenación.

**Nota**: No se agrega una nueva dimensión, se concatena los tensores en la dimensión especificada.

In [39]:
x = torch.randn(3, 5)
y = torch.randn(3, 5)

concatenated = torch.cat([x, y], dim=0)  # Concatenación a lo largo de la dimensión 0

In [40]:
concatenated

tensor([[-0.1340, -0.7660,  0.1371,  0.1426, -0.8234],
        [-1.0204, -1.2982, -0.4539,  0.8850, -0.2362],
        [-0.2252, -0.2561, -0.5008, -0.3745, -0.1446],
        [-2.1454, -0.3334, -0.6949, -0.0284,  0.7899],
        [ 0.6681, -1.0915,  0.7145, -1.9156,  0.0641],
        [ 1.0462,  0.2604, -0.2178,  2.3955, -0.6390]])

### **1.5 Indexing**

Esta sección será más práctica, dado que se tendrá que manipular cada tensor utilizando el slicing.

#### **1.5.1 Indexing a Tensores 2D**

In [ ]:
# Crea un tensor aleatorio de tamaño 6x4 y utiliza una semilla de valor 5
torch.manual_seed(5)

random_tensor = torch.rand(size=(6,4))
random_tensor

In [ ]:
# Muestra su forma y dimensión
random_tensor.shape, random_tensor.ndim

In [ ]:
# Muestra la primera fila
random_tensor[0]

In [82]:
# Muestra la última fila
random_tensor[-1]

tensor([0.6698, 0.2615, 0.0407, 0.7850])

In [83]:
# Muestra la primera columna, recuerda que los : indica que selecciono todos los elementos de la fila
random_tensor[:, 0]

tensor([0.8303, 0.9201, 0.0333, 0.0724, 0.9809, 0.6698])

In [ ]:
# Muestra la última columna, recuerda que los : indica que selecciono todos los elementos de la fila
random_tensor[:, -1]

In [84]:
# Muestra las 3 primeras filas, recuerda que puedes no indicar el índice de inicio, ya que por detrás se utiliza automáticamente
random_tensor[:3]

tensor([[0.8303, 0.1261, 0.9075, 0.8199],
        [0.9201, 0.1166, 0.1644, 0.7379],
        [0.0333, 0.9942, 0.6064, 0.5646]])

In [85]:
# Muestra las 2 últimas columnas
random_tensor[:, 2:]

tensor([[0.9075, 0.8199],
        [0.1644, 0.7379],
        [0.6064, 0.5646],
        [0.7150, 0.5793],
        [0.0566, 0.9201],
        [0.0407, 0.7850]])

In [ ]:
# Crea una matriz de ceros de tamaño 3x5 

In [ ]:
# Convierte toda la primera fila en unos

In [ ]:
# Convierte toda la última columna en números 5 fila en unos


#### **1.5.2 Slicing a Tensores 3D**

In [16]:
import torch

In [18]:
torch.manual_seed(5)
random_tensor = torch.rand(size=(3,5,6))

In [ ]:
# Muestra el tensor que creamos, donde es una secuencia de 3 matrices de tamaño 5x6

In [20]:
# Podemos seleccionar el último batch
random_tensor[-1]

tensor([[0.2225, 0.2148, 0.3662, 0.3384, 0.1600, 0.9041],
        [0.5557, 0.7280, 0.8709, 0.1760, 0.8817, 0.2495],
        [0.4204, 0.8784, 0.9610, 0.9389, 0.7876, 0.9647],
        [0.3198, 0.4682, 0.3290, 0.4633, 0.4392, 0.7671],
        [0.8437, 0.1399, 0.2239, 0.3462, 0.5668, 0.3059]])

In [ ]:
# Podemos verificar esto viendo su forma
random_tensor[-1].shape

torch.Size([5, 6])

In [ ]:
# Del último batch convierte la primera fila y columna en unos, y convierte la última fila y columna en unos. Nota:
# Existen dos formas de realizar esto con la notación del corchete

In [ ]:
# Ahora los valores encerrados dentro de los valores que son unos, conviértelos en cero

### **1.6 PyTorch y NumPy**

#### **1.6.1 NumPy a PyTorch**

In [86]:
import numpy as np
import torch

In [87]:
array = np.arange(1,10)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
tensor = torch.from_numpy(array)
tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### **1.6.2 PyTorch a NumPy**

In [45]:
tensor = torch.arange(0,9)
tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [46]:
array = tensor.numpy()
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

## **2. Ejercicios**

1. Crea un tensor de 3x3 de números aleatorios.
2. Crea un tensor de 5x5 de ceros.
3. Crea un tensor de 4x4 de unos.
4. Crea un tensor de 2x3 de números enteros (por ejemplo, usando torch.randint).
5. Suma y resta dos tensores de igual forma.
6. Multiplica y divide dos tensores de igual forma.
7. Aplica la función ``torch.abs()`` a un tensor con valores negativos.
8. Crea un tensor de forma (2, 3, 4), luego aplícale:
    * ``reshape()`` para cambiar su forma a (6, 4).
    * ``squeeze()`` para eliminar dimensiones de tamaño 1.
    * ``unsqueeze()`` para agregar una nueva dimensión en la posición 0.
    * ``view()`` para cambiar la forma a (3, 8).
9. Crea dos tensores x y y de forma (3, 4).
    * Usa torch.cat() para concatenarlos a lo largo de la dimensión 0 y la dimensión 1.
    * Usa torch.stack() para apilarlos a lo largo de una nueva dimensión.
10. Crea un tensor de forma (3, 2) y usa torch.transpose() o .T para transponerlo.
11. Crea un tensor de forma (2, 3, 4) y usa torch.permute() para reorganizar las dimensiones a (4, 2, 3).
12. Crea un tensor de forma (2, 3, 4) y usa view() para aplanarlo a un tensor de forma (24,).

## **3. Referencias**

A continuación, se deja recursos de donde se obtuvo la información entregada anteriormente para profundizar.

1. [Aprender Pytorch](https://www.learnpytorch.io/00_pytorch_fundamentals/#00-pytorch-fundamentals)